#ifndef VS_COMPUTER_H_INCLUDED
#define VS_COMPUTER_H_INCLUDED



HINSTANCE g_hinst;
LRESULT CALLBACK WndProcc(HWND hwnd, UINT Message, WPARAM wParam, LPARAM lParam);

#endif // VS_COMPUTER_H_INCLUDED
